### ISSUE TITLE
Getting Started to use the CoSim Simulator

### ISSUE THREAD

**Issue by bg-sumu** [cetran-sg/CoSim#1]
I went through the Documentation and was confused on what to do after map creation ? Is there a sample Scenario which i could go through ? I want to mainly run the Simulation using Carla and SUMO.

**Comment by vjyrshn** [comment]
You may script your own scenarios using Carla's Python API inside scenarioManager.py. There is a template scenario provided there but the coordinates in that scenario may not match your map. You can edit those coordinates and spawn points based on your map positions.

The scenarioManager is instantiated from cosimManager under scenarioPlayer. You can modify scenarioPlayer to configure how and when you want your scenario to start/stop. scenarioPlayer needs to be enabled using a flag in config.py. By default, this flag is set to TRUE.
